//Matrix storing all information related to rides.
var attractionsOwned = {
    playarea: {
        name: "playarea",
        fullName: "Play Area",
        desc: "Description...",
        costBase: 25,
        costNext: 25,
        amountOwned: 0,
        addCapacity: 5,
        addMoney: 1,
        addGuest: 1,
        duration: 6,
        durationRemaining: 6,
        operating: false,
        operatorOwned: 0,
    },
    
    bouncycastle: {
        name: "bouncycastle",
        fullName: "Bouncy Castle",
        desc: "Description...",
        costBase: 100,
        costNext: 100,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    carousel: {
        name: "carousel",
        fullName: "Carousel",
        desc: "Description...",
        costBase: 400,
        costNext: 400,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    teacups: {
        name: "teacups",
        fullName: "Teacups",
        desc: "Description...",
        costBase: 1600,
        costNext: 1600,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    chairswing: {
        name: "chairswing",
        fullName: "Chair Swing",
        desc: "Description...",
        costBase: 4800,
        costNext: 4800,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    ferriswheel: {
        name: "ferriswheel",
        fullName: "Ferris Wheel",
        desc: "Description...",
        costBase: 24000,
        costNext: 24000,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    runawaytrain: {
        name: "runawaytrain",
        fullName: "Runaway Train",
        desc: "Description...",
        costBase: 120000,
        costNext: 120000,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    dodgems: {
        name: "dodgems",
        fullName: "Dodgems",
        desc: "Description...",
        costBase: 480000,
        costNext: 480000,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    funhouse: {
        name: "funhouse",
        fullName: "Funhouse",
        desc: "Description...",
        costBase: 1440000,
        costNext: 1440000,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    disko: {
        name: "disko",
        fullName: "Disko",
        desc: "Description...",
        costBase: 2880000,
        costNext: 2880000,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    hauntedhouse: {
        name: "hauntedhouse",
        fullName: "Haunted House",
        desc: "Description...",
        costBase: 5760000,
        costNext: 5760000,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    lasertag: {
        name: "lasertag",
        fullName: "Laser Tag",
        desc: "Description...",
        costBase: 23040000,
        costNext: 23040000,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    twister: {
        name: "twister",
        fullName: "Twister",
        desc: "Description...",
        costBase: 92160000,
        costNext: 92160000,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    simulator: {
        name: "simulator",
        fullName: "Motion Simulator",
        desc: "Description...",
        costBase: 460800000,
        costNext: 460800000,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    spincoaster: {
        name: "spincoaster",
        fullName: "Spinning Coaster",
        desc: "Description...",
        costBase: 921600000,
        costNext: 921600000,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    monorail: {
        name: "monorail",
        fullName: "Park Monorail",
        desc: "Description...",
        costBase: 3686400000,
        costNext: 3686400000,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    woodcoaster: {
        name: "woodcoaster",
        fullName: "Classic Wooden Coaster",
        desc: "Description...",
        costBase: 11059200000,
        costNext: 11059200000,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    enterprise: {
        name: "enterprise",
        fullName: "Enterprise",
        desc: "Description...",
        costBase: 44236800000,
        costNext: 44236800000,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    waltzer: {
        name: "waltzer",
        fullName: "Waltzer",
        desc: "Description...",
        costBase: 221184000000,
        costNext: 221184000000,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    gocarts: {
        name: "gocarts",
        fullName: "Go Karts",
        desc: "Description...",
        costBase: 1105920000000,
        costNext: 1105920000000,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    pirateship: {
        name: "pirateship",
        fullName: "Pirate Ship",
        desc: "Description...",
        costBase: 4423680000000,
        costNext: 4423680000000,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    droptower: {
        name: "droptower",
        fullName: "Drop Tower",
        desc: "Description...",
        costBase: 22118400000000,
        costNext: 22118400000000,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    launchedcoaster: {
        name: "launchedcoaster",
        fullName: "Launched Rollercoaster",
        desc: "Description...",
        costBase: 88473600000000,
        costNext: 88473600000000,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    logflume: {
        name: "logflume",
        fullName: "Log Flume",
        desc: "Description...",
        costBase: 353894000000000,
        costNext: 353894000000000,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    loopcoaster: {
        name: "loopcoaster",
        fullName: "Looping Coaster",
        desc: "Description...",
        costBase: 1061680000000000,
        costNext: 1061680000000000,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    rapids: {
        name: "rapids",
        fullName: "Rapids",
        desc: "Description...",
        costBase: 3185050000000000,
        costNext: 3185050000000000,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    standupcoaster: {
        name: "standupcoaster",
        fullName: "Standing Coaster",
        desc: "Description...",
        costBase: 12740200000000000,
        costNext: 12740200000000000,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    },
    
    vrcoaster: {
        name: "vrcoaster",
        fullName: "VR Coaster",
        desc: "Description...",
        costBase: 50960800000000000,
        costNext: 50960800000000000,
        amountOwned: 0,
        addCapacity: 0,
        addMoney: 0,
        addGuest: 0,
        duration: 0,
        durationRemaining: 0,
        operating: false,
        operatorOwned: 0,
    }
};

var staffOwned = {
    operator: {
        name: "operator",
        fullName: "Ride Operator",
        desc: "Purchasing a ride operator allows you to hire staff to operate the rides within the park. The more of these the more automated the rides become.",
        costBase: 75,
        costNext: 75,
        amountOwned: 0
    }
};

function initialiseRides() {
    var ridePlacement = true;
    
    for(var ride in attractionsOwned){
        if(attractionsOwned.hasOwnProperty(ride)){
            var rideName = attractionsOwned[ride];
        
            rideName.addMoney = Math.round(rideName.costBase * 0.6);
            rideName.duration = Math.round(rideName.addMoney * 1.075);
            rideName.durationRemaining = rideName.duration;
            
            if(ridePlacement === false){
                $('#rideContainer').append('<div class="col m4 s12"><div class="card small"><div class="card-image"><img src="img/attractionImg/' + rideName.name + '.png"><span class="card-title">' + rideName.fullName + '</span></div><div class="card-content black-text"> <div class="currentLevel btn-floating btn-small purple lighten-2"><span id="' + rideName.name + 'Count">' + rideName.amountOwned + '</span></div><div class="progress"><div class="determinate" id="' + rideName.name + 'Progress" style="width: 0%"></div></div><p>' + rideName.duration + ' Duration, &Phi;' + numberWithCommas(rideName.addMoney) + ' Additional Money and ' + rideName.addGuest + ' additional guests. Operator Owned? ' + rideName.operatorOwned + '</p></div><div class="card-action"><a class="purple-text text-lighten-2" onclick="purchaseAttraction(\'' + rideName.name + '\');" href="#/">Upgrade ' + rideName.fullName + ' (&Phi;<span id="next' + rideName.name + 'Cost"> ' + numberWithCommas(rideName.costNext) + '</span>)</a><a onclick="operateAttraction(\'' + rideName.name + '\');" href="#/" class="right purple-text text-lighten-2">Operate Attraction</a></div></div></div>');
                ridePlacement = true;
            }else{
                $('#rideContainer').append('<div class="col m4 offset-m2 s12"><div class="card small"><div class="card-image"><img src="img/attractionImg/' + rideName.name + '.png"><span class="card-title">' + rideName.fullName + '</span></div><div class="card-content black-text"> <div class="currentLevel btn-floating btn-small purple lighten-2"><span id="' + rideName.name + 'Count">' + rideName.amountOwned + '</span></div><div class="progress"><div class="determinate" id="' + rideName.name + 'Progress" style="width: 0%"></div></div><p>' +  rideName.duration + ' Duration,  &Phi; ' + numberWithCommas(rideName.addMoney) + 'Additional Money and ' + rideName.addGuest + ' additional guests. Operator Owned? ' + rideName.operatorOwned + '</p></div><div class="card-action"><a class="purple-text text-lighten-2" onclick="purchaseAttraction(\''+ rideName.name + '\');" href="#/">Upgrade ' + rideName.fullName + ' (&Phi; <span id="next' + rideName.name + 'Cost">' + numberWithCommas(rideName.costNext) + '</span>)</a><a onclick="operateAttraction(\'' + rideName.name + '\');" href="#/" class="right purple-text text-lighten-2">Operate Attraction</a></div></div></div>');
                ridePlacement = false;
            }
        }
    }
    
    for(var staff in staffOwned){
        if(staffOwned.hasOwnProperty(staff)){
            var staffName = staffOwned[staff];
            
            $('#staffContainer').append('<div class="col m8 offset-m2 s12"><div class="card medium"><div class="card-image"><img src="https://www.cedarpoint.com/images/rides/1_IMG_18151.jpg"><span class="card-title">' + staffName.fullName + '</span></div><div class="card-content black-text"><div class="currentLevel btn-floating btn-small purple lighten-2"><span id="' + staffName.name + 'Count">' + staffName.amountOwned + '</span></div><p>' + staffName.desc + '</p></div><div class="card-action"><a class="purple-text text-lighten-2" onclick="purchaseStaff(\'' + staffName.name + '\');" href="#">Buy ' + staffName.fullName + ' (&Phi;<span id="' + staffName.name + 'Cost">' + staffName.costNext + '</span>)</a></div></div></div>');
        }
    }
}